name: geoaquacrop
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - scipy
  - xarray
  - dask
  - shapely
  - requests
  - geopandas
  - rasterio
  - pandas
  - cdsapi
  - netcdf4
  - rioxarray
  - owslib
  - soilgrids
  - dash-bootstrap-components
  - plotly
  - pip
  - pip:
    - aquacrop
    - dnspython
